README.md
src/App.tsx
src/lib/wallet.ts
src/utils/displayFunctions.tsx

Fixes: #13 
Using https://fkhadra.github.io/react-toastify/promise/#toastpromise would be a little cleaner but not sure it's worth the effort

user feedback on voting

---

index.html
package.json
src/App.tsx
src/components/GovernanceTools.tsx
src/components/HistoryPanel.tsx
src/components/ProposeParamChange.tsx
src/components/ProposePauseOffers.tsx
src/components/PsmPanel.tsx
src/components/VotePanel.tsx
src/components/inputs.tsx
src/components/questions.tsx
src/utils/displayFunctions.tsx
tailwind.config.cjs
yarn.lock

UX Improvements

---

src/components/VotePanel.tsx
src/components/questions.tsx
src/config.ts
src/utils/helpers.ts
yarn.lock

Closes: #14 
This queries the history of `latestQuestion` to show all the questions available from RPC. Then it renders questions for which the deadline hasn't passed.

14 vote multiple

---

package.json
patches/vitest+0.25.3.patch
src/components/questions.tsx
src/lib/governance.test.js
src/lib/governance.ts
src/test/stub.test.ts
yarn.lock

fix: feedback for noChange/dontUpdate

---

package.json
src/components/HistoryPanel.tsx
src/components/VotePanel.tsx
src/components/questions.tsx
src/govTypes.ts
src/lib/governance.ts
src/utils/helpers.ts
src/utils/updates.ts
src/vite-env.d.ts
yarn.lock

use types from https://github.com/Agoric/agoric-sdk/pull/6608 as source of truth

import governance,casting types

---

src/components/PsmPanel.tsx

[proposal 17](https://bigdipper.live/agoric/proposals/17) has reached quorum; it should take effect Mon, 5 Dec at around 10:30am PT.
cc @otoole-brendan @turadg @FredRadford @samsiegart

add DAI_axl, DAI_grv per proposal 17

---

src/components/AcceptInvitation.tsx
src/components/Eligibility.tsx
src/components/GovernanceTools.tsx
src/components/ProposeParamChange.tsx
src/components/ProposePauseOffers.tsx
src/components/PsmPanel.tsx
src/components/VaultParamChange.tsx
src/components/VaultsPanel.tsx
src/components/inputs.tsx
src/components/questions.tsx
src/lib/chainInfo.ts
src/lib/rpc.ts
src/lib/wallet.ts

refs https://github.com/Agoric/dapp-econ-gov/issues/32

Change Vault Manager Params

---

src/components/DirectorParamChange.tsx
src/components/HistoryPanel.tsx
src/components/PauseVaultDirectorOffers.tsx
src/components/ProposeParamChange.tsx
src/components/ProposePauseOffers.tsx
src/components/VaultParamChange.tsx
src/components/VaultsPanel.tsx
src/components/questions.tsx
src/lib/wallet.ts

fixes https://github.com/Agoric/dapp-econ-gov/issues/32
fixes https://github.com/Agoric/dapp-econ-gov/issues/30

Vault director params

---

src/components/PauseVaultDirectorOffers.tsx

feat: clarify pause offers choices

---

src/components/BurnIst.tsx
src/components/CharterGuidance.tsx
src/components/VaultsPanel.tsx
src/components/VotePanel.tsx
src/components/inputs.tsx
src/components/questions.tsx
src/lib/governance.test.js
src/lib/governance.ts
src/lib/wallet.ts
src/styles/utilities.css

fixes: #33 
Tried voting to burn on a local network when there were no reserves, and saw a credible looking error in the contract on-chain.

feat: manual burn IST

---

src/components/PauseLiquidations.tsx
src/components/VaultsPanel.tsx

fixes: https://github.com/Agoric/dapp-econ-gov/issues/34

feat: pause deposit collateral

---

src/components/PauseVaultDirectorOffers.tsx
src/components/VaultParamChange.tsx
src/components/VotePanel.tsx
src/components/questions.tsx
src/lib/makeImportContext.ts
src/lib/rpc.ts
src/lib/wallet.ts
src/utils/displayFunctions.tsx

fixes #49 
Makes the dapp work with smallcaps. I'm pretty confident the PSM stuff is still backwards compatible.
Also fixed the vault managers' vstorage paths since those were changed. Did not make that part backwards compatible, so no guarantees for devnet. We could consider pointing devnet users (and EC if worst-case mainnet is broken) to a different deployment, since we have one for every commit hash.
Accepted invitations, made and voted on some proposals successfully. Did not test exhaustively with every type of proposal, but did some from both PSM and Vaults.

fix: smallcaps compatible

---

src/components/DirectorParamChange.tsx
src/components/VaultParamChange.tsx
src/components/questions.tsx
src/utils/displayFunctions.tsx

fixes https://github.com/Agoric/dapp-econ-gov/issues/48
fixes https://github.com/Agoric/dapp-econ-gov/issues/54

feat: display desirable param names

---

src/App.tsx
src/config.ts
src/lib/rpc.ts
src/lib/wallet.ts
src/utils/displayFunctions.tsx

closes: #23
- feat: put "econgov" in the offer id
- feat: use archive server for main
Plus various refactorings to consolidate configuration and network-dependent logic

archive node for main

---

src/components/PsmPanel.tsx

cc @ivanlei @samsiegart @0xpatrickdev @turadg

feat(PsmPanel): USDC, USDT from #59, #60

---

package.json
yarn.lock

fixes https://github.com/Agoric/dapp-econ-gov/issues/78

fix: update framer to solve voting bug

---

src/lib/wallet.ts

Fixes https://github.com/Agoric/dapp-econ-gov/issues/84

fix: default to mainnet

---

src/config.ts

fixes https://github.com/Agoric/dapp-econ-gov/issues/95

fix: change explorer from bigdipper to guru

---

README.md

Added section to readme which describes how to run e2e tests

docs: updated readme to inlude test info

---

.github/workflows/e2e_tests.yml

trigger e2e tests for opened and reopned events
